import requests
import json
import html

parameters = {
    "amount": 10,
    "type": "boolean",
    }
response = requests.get("https://opentdb.com/api.php", params=parameters)
response.raise_for_status()
question_data = response.json()["results"]






# question_data = [
#     {"text": "A slug's blood is green.", "answer": "True"},
#     {"text": "The loudest animal is the African Elephant.", "answer": "False"},
#     {
#         "text": "Approximately one quarter of human bones are in the feet.",
#         "answer": "True",
#     },
#     {
#         "text": "The total surface area of a human lungs is the size of a football pitch.",
#         "answer": "True",
#     },
#     {
#         "text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.",
#         "answer": "True",
#     },
#     {
#         "text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
#         "answer": "False",
#     },
#     {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
#     {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
#     {"text": "Google was originally called 'Backrub'.", "answer": "True"},
#     {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
#     {
#         "text": "No piece of square dry paper can be folded in half more than 7 times.",
#         "answer": "False",
#     },
#     {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
# ]


# questions_new = [
#     {
#         "type": "boolean",
#         "difficulty": "hard",
#         "category": "History",
#         "question": "The Battle of Trafalgar took place on October 23rd, 1805",
#         "correct_answer": "False",
#         "incorrect_answers": ["True"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "hard",
#         "category": "Entertainment: Video Games",
#         "question": "The video game &quot;Fuel&quot; has an open world that is 5,560 square miles?",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "easy",
#         "category": "General Knowledge",
#         "question": "Slovakia is a member of European Union-",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "medium",
#         "category": "History",
#         "question": "Theodore Roosevelt Jr. was the only General involved in the initial assault on D-Day.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "medium",
#         "category": "Entertainment: Music",
#         "question": "For his performance at ComplexCon 2016 in Long Beach, California, Skrillex revived his &quot;Mothership&quot; set piece for one night only.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "medium",
#         "category": "Science: Computers",
#         "question": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;",
#         "correct_answer": "False",
#         "incorrect_answers": ["True"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "medium",
#         "category": "Entertainment: Video Games",
#         "question": "The Ace Attorney trilogy was suppose to end with &quot;Phoenix Wright: Ace Attorney &minus; Trials and Tribulations&quot; as its final game.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "easy",
#         "category": "Entertainment: Music",
#         "question": "A Saxophone is a brass instrument.",
#         "correct_answer": "False",
#         "incorrect_answers": ["True"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "medium",
#         "category": "Science: Computers",
#         "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "easy",
#         "category": "General Knowledge",
#         "question": "Bulls are attracted to the color red.",
#         "correct_answer": "False",
#         "incorrect_answers": ["True"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "medium",
#         "category": "Entertainment: Music",
#         "question": "3 members of 2 Live Crew were arrested for playing songs from their album, As Nasty As They Wanna Be, live.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "hard",
#         "category": "Entertainment: Books",
#         "question": "Harry Potter was born on July 31st, 1980.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "easy",
#         "category": "Entertainment: Television",
#         "question": "In &quot;Doctor Who&quot;, the Doctor gets his TARDIS by stealing it.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "easy",
#         "category": "Science &amp; Nature",
#         "question": "An average human can go two weeks without water.",
#         "correct_answer": "False",
#         "incorrect_answers": ["True"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "easy",
#         "category": "Science: Computers",
#         "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
#         "correct_answer": "False",
#         "incorrect_answers": ["True"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "medium",
#         "category": "Entertainment: Video Games",
#         "question": "In &quot;Overwatch,&quot; an allied McCree will say &quot;Step right up&quot; upon using his ultimate ability Deadeye.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "easy",
#         "category": "Animals",
#         "question": "Rabbits can&#039;t vomit.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "easy",
#         "category": "Science: Mathematics",
#         "question": "The sum of any two odd integers is odd.",
#         "correct_answer": "False",
#         "incorrect_answers": ["True"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "easy",
#         "category": "Entertainment: Video Games",
#         "question": "In the &quot;S.T.A.L.K.E.R.&quot; series, the Freedom faction wishes to destroy the supernatural area known as  &quot;the Zone&quot;.",
#         "correct_answer": "False",
#         "incorrect_answers": ["True"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "easy",
#         "category": "Entertainment: Video Games",
#         "question": "In the &quot;Half-Life&quot; series, &quot;H.E.V&quot; stands for &quot;Hazardous Evasiveness Vest&quot;",
#         "correct_answer": "False",
#         "incorrect_answers": ["True"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "easy",
#         "category": "Entertainment: Japanese Anime &amp; Manga",
#         "question": "Clefairy was intended to be Ash&#039;s starting Pok&eacute;mon in the pilot episode of the cartoon.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "medium",
#         "category": "Entertainment: Video Games",
#         "question": "In Half-Life 2, if you play the zombies&#039; speech in reverse, they actually speak coherent English.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "hard",
#         "category": "Entertainment: Video Games",
#         "question": "In the game &quot;Melty Blood Actress Again Current Code&quot;, you can enter Blood Heat mode in Half Moon style.",
#         "correct_answer": "False",
#         "incorrect_answers": ["True"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "hard",
#         "category": "Science: Computers",
#         "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
#         "correct_answer": "False",
#         "incorrect_answers": ["True"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "easy",
#         "category": "Entertainment: Japanese Anime &amp; Manga",
#         "question": "Kiznaiver is an adaptation of a manga.",
#         "correct_answer": "False",
#         "incorrect_answers": ["True"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "medium",
#         "category": "Entertainment: Video Games",
#         "question": "Metal Gear Solid V: The Phantom Pain runs on the Fox Engine.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "medium",
#         "category": "General Knowledge",
#         "question": "Haggis is traditionally ate on Burns Night.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "easy",
#         "category": "Entertainment: Japanese Anime &amp; Manga",
#         "question": "In the 1988 film &quot;Akira&quot;, Tetsuo ends up destroying Tokyo.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "medium",
#         "category": "Entertainment: Video Games",
#         "question": "The game Garry&#039;s Mod originally took assets and codes from the popular Half Life 2 mod JBmod.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "easy",
#         "category": "Entertainment: Video Games",
#         "question": "Tony Hawk&#039;s extreme sports videogames revolve around performing professional BMX tricks.",
#         "correct_answer": "False",
#         "incorrect_answers": ["True"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "medium",
#         "category": "Geography",
#         "question": "Vietnam is the only country in the world that starts with V. ",
#         "correct_answer": "False",
#         "incorrect_answers": ["True"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "easy",
#         "category": "Science: Gadgets",
#         "question": "Microphones can be used not only to pick up sound, but also to project sound similar to a speaker.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "easy",
#         "category": "Mythology",
#         "question": "A wyvern is the same as a dragon.",
#         "correct_answer": "False",
#         "incorrect_answers": ["True"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "easy",
#         "category": "Entertainment: Video Games",
#         "question": "Pac-Man was invented by the designer Toru Iwatani while he was eating pizza.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "easy",
#         "category": "History",
#         "question": "United States President John F. Kennedy was assassinated during his presidential motorcade in Atlanta, Georgia on November 22nd, 1963.",
#         "correct_answer": "False",
#         "incorrect_answers": ["True"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "easy",
#         "category": "Art",
#         "question": "Leonardo da Vinci was not the creator of the Mona Lisa.",
#         "correct_answer": "False",
#         "incorrect_answers": ["True"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "medium",
#         "category": "Entertainment: Video Games",
#         "question": "Resident Evil 4 was originally meant to be a Nintendo GameCube exclusive.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "medium",
#         "category": "Geography",
#         "question": "You could walk from Norway to North Korea while only passing through Russia.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "medium",
#         "category": "Science &amp; Nature",
#         "question": "A person can get sunburned on a cloudy day.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "medium",
#         "category": "Vehicles",
#         "question": "Arriva is owned by the Deutsche Bahn.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "medium",
#         "category": "Entertainment: Video Games",
#         "question": "In &quot;Resident Evil&quot;, only Chris has access to the grenade launcher.",
#         "correct_answer": "False",
#         "incorrect_answers": ["True"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "easy",
#         "category": "History",
#         "question": "The United States of America declared their independence from the British Empire on July 4th, 1776.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "hard",
#         "category": "Entertainment: Video Games",
#         "question": "In Undertale, having a &quot;Fun Value&quot; set to 56-57 will play the &quot;Wrong Number Song Call&quot;.",
#         "correct_answer": "False",
#         "incorrect_answers": ["True"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "medium",
#         "category": "Entertainment: Board Games",
#         "question": "&quot;Rich Uncle Pennybags&quot; from the board game &quot;Monopoly&quot; wears a monocle.",
#         "correct_answer": "False",
#         "incorrect_answers": ["True"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "medium",
#         "category": "Art",
#         "question": "Vincent van Gogh cut off one of his ears.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "easy",
#         "category": "History",
#         "question": "Kublai Khan is the grandchild of Genghis Khan?",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "medium",
#         "category": "History",
#         "question": "Adolf Hitler was accepted into the Vienna Academy of Fine Arts.",
#         "correct_answer": "False",
#         "incorrect_answers": ["True"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "easy",
#         "category": "Entertainment: Japanese Anime &amp; Manga",
#         "question": "In Pok&eacute;mon, Ash&#039;s Pikachu refuses to go into a pokeball.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "medium",
#         "category": "General Knowledge",
#         "question": "Cucumbers are usually more than 90% water.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
#     {
#         "type": "boolean",
#         "difficulty": "medium",
#         "category": "Entertainment: Television",
#         "question": "Klingons once had a period of Democracy in their history, they referred to it as the &quot;Dark Times&quot;.",
#         "correct_answer": "True",
#         "incorrect_answers": ["False"],
#     },
# ]
